### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by NatNyt** [botkalista/discord.js.userbot#11]
I dont know how to fix this 
```
    this.id = data.id;
                   ^

TypeError: Cannot read properties of undefined (reading 'id')
    at ClientApplication._patch (E:\Voucher_Grabber\node_modules\discord.js\src\structures\interfaces\Application.js:24:20)
    at ClientApplication._patch (E:\Voucher_Grabber\node_modules\discord.js\src\structures\ClientApplication.js:24:11)
    at new Application (E:\Voucher_Grabber\node_modules\discord.js\src\structures\interfaces\Application.js:16:10)
    at new ClientApplication (E:\Voucher_Grabber\node_modules\discord.js\src\structures\ClientApplication.js:14:5)
    at Object.module.exports [as READY] (E:\Voucher_Grabber\node_modules\discord.js\src\client\websocket\handlers\READY.js:23:26)
    at WebSocketManager.handlePacket (E:\Voucher_Grabber\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (E:\Voucher_Grabber\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (E:\Voucher_Grabber\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (E:\Voucher_Grabber\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)
```

**Comment by dark-swordsman** [comment]
I'm not sure about the specifics of the issue, but it appears that in `/discord.js/src/client/websocket/handlers/READY.js`, when it does `data.application`, the `application` property is missing from `data` and therefore is undefined.

I have no broader knowledge of the discord api or discord.js, but my best guess is that they changed the structure of users and put stricter enforcements on using API keys for users.

**Comment by Kaid3n22** [comment]
It is just as @dark-swordsman has said. I have found a workaround by setting the data.application within the script. Here is how it looks:
```
'use strict';

const ClientApplication = require('../../../structures/ClientApplication');
let ClientUser;

module.exports = (client, { d: data }, shard) => {
  if (client.user) {
    client.user._patch(data.user);
  } else {
    if (!ClientUser) ClientUser = require('../../../structures/ClientUser');
    client.user = new ClientUser(client, data.user);
    client.users.cache.set(client.user.id, client.user);
  }

  for (const guild of data.guilds) {
    guild.shardId = shard.id;
    client.guilds._add(guild);
  }

  data.application = {id: 'YOURID', flags: 262144}

  if (client.application) {
    client.application._patch(data.application);
  } else {
    client.application = new ClientApplication(client, data.application);
  }

  shard.checkReady();
};

**Comment by YeaTheMen** [comment]
Hey thanks @Kaid3n22  but what script to we place fix into? Do we put it in our bots main script or in one of the discord.js modules etc?
