### ISSUE TITLE
(node:1873) UnhandledPromiseRejectionWarning: Error: Not supported

### ISSUE THREAD

**Issue by gabltz** [botkalista/discord.js.userbot#2]
got this error while  starting my bot :

`(node:1873) UnhandledPromiseRejectionWarning: Error: Not supported
    at WebSocketManager.client.ws.connect (/home/debian/Discord/Music-bot/node_modules/discord.js.userbot/index.js:28:68)
    at Client.login (/home/debian/Discord/Music-bot/node_modules/discord.js/src/client/Client.js:223:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:1873) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1873) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by botkalista** [comment]
Fixed 9908566eced9bde71fb48d768d379927ef5f6c41
